name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Problem or motivation
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe what you'd like to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
    validations:
      required: false
